SqlTemplate depends on flyway/liquibase execution
mybatis/spring-boot-starter pull request #648
Opened 2022-05-06 03:49 UTC by eddumelendez

See gh-537

2022-05-07 00:29 UTC, eddumelendez commented
Hi @kazuki43zoo 
Can you help me with the following tests `testCustomFreeMarkerConfigUsingConfigurationProperty,` `testCustomThymeleafConfigUsingConfigurationProperty`, `testCustomVelocityConfig`, `testCustomVelocityConfigUsingConfigurationProperty`, please?

I am not quite familiar with the template support.

2022-05-15 12:06 UTC, kazuki43zoo requested changes

2022-05-15 12:06 UTC, kazuki43zoo commented on mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisLanguageDriverAutoConfigurationTest.java
> +  static class MyAutoConfiguration {
@eddumelendez 

You can avoid error using `@EnableConfigurationProperties` because theses tests use configuration properties feature.

2022-05-15 12:06 UTC, kazuki43zoo commented on mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisLanguageDriverAutoConfigurationTest.java
> -    VelocityFacade.destroy();
This code is needed. Please add following code.

```java
  @BeforeAll
  @AfterAll
  static void initializeVelocity() {
    VelocityFacade.destroy();
  }
```

2022-05-15 16:05 UTC, eddumelendez commented
thank you @kazuki43zoo ! PR updated

2022-05-29 01:28 UTC, kazuki43zoo requested changes
I've added trivial comments. And please rebase from latest master branch.

2022-05-29 01:28 UTC, kazuki43zoo commented on mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisDependsOnDatabaseInitializationDetector.java
> + */
Want to add `@since 2.3.0'.

2022-05-29 01:28 UTC, kazuki43zoo commented on mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/TestAutoConfigurationPackage.java
> +import java.lang.annotation.*;
We does not use wildcard imports.

2022-05-29 01:28 UTC, kazuki43zoo commented on mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/TestAutoConfigurationPackage.java
> + * @author Phillip Webb
`@author Eddú Meléndez` ?

2022-05-29 01:28 UTC, kazuki43zoo commented on mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/TestAutoConfigurationPackageRegistrar.java
> + * @author Phillip Webb
`@author Eddú Meléndez` ?

2022-05-29 01:35 UTC, kazuki43zoo commented
Note: This change work with Spring Boot 2.5+.

2022-05-29 01:48 UTC, eddumelendez commented
PR updated

2022-05-29 02:04 UTC, kazuki43zoo approved these changes

2022-05-29 02:36 UTC, merged

2022-05-29 02:37 UTC, kazuki43zoo commented
@eddumelendez Thanks!!